package(default_visibility = ["//visibility:public"])

cc_test(
    name = "file_consumer_test",
    srcs = ["file_consumer_test.cc"],
    deps = [
        "//src/framework/core",
        "//src/framework/queue",
        "//src/framework/consumer",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "byte_sink_test",
    srcs = ["byte_sink_test.cc"],
    deps = [
        "//src/framework/io",
        "@com_google_googletest//:gtest_main",
    ],
)
