package(default_visibility = ["//visibility:public"])

cc_library(
    name = "webrtc_backend",
    srcs = [
        "webrtc_backend.cc",
        "whip_session.cc",
    ],
    hdrs = [
        "webrtc_backend.h",
        "webrtc_raii.h",
        "whip_session.h",
    ],
    alwayslink = True,
    deps = [
        "@video_stream//src/api:stream_api",
        "@video_stream//src/core:stream_core",
        "@libdatachannel//:datachannel",
        "@cpp_network//:cpp_network",
        "@video_codec//src/framework/core:log_slot",
    ],
)