package(default_visibility = ["//visibility:public"])

cc_test(
    name = "pixel_convert_test",
    srcs = ["pixel_convert_test.cc"],
    deps = [
        "@video_codec//src/framework/core",
        "@video_codec//src/framework/convert/libyuv:pixel_convert",
        "@com_google_googletest//:gtest_main",
    ],
)
