package(default_visibility = ["//visibility:public"])

cc_test(
    name = "yuv_convert_test",
    srcs = ["yuv_convert_test.cc"],
    deps = [
        "//src/framework/core",
        "//src/framework/utils",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "stride_test",
    srcs = ["stride_test.cc"],
    deps = [
        "//src/framework/core",
        "//src/framework/utils",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "pcm_convert_test",
    srcs = ["pcm_convert_test.cc"],
    deps = [
        "//src/framework/core",
        "//src/framework/utils",
        "@com_google_googletest//:gtest_main",
    ],
)
